# Change these first
owner: chadburrus # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Personal
    url: https://chadburrus.com
  - name: Enchanted Vacations
    url: https://yourenchantingvacation.com
  - name: Casey
    url: https://caseyburrus.org
  - name: Woodside
    url: https://woodside-community.church

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
